on:
 workflow_dispatch:
 schedule:
  - cron: "0 */2 * * *"
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker-compose -f docker-compose.yml build crawler
    - name: crawl
      run: |
        touch data/$(date -u +"%Y-%m-%d").jsonlines.gz;
        tmp_medimops=$(mktemp)
        docker-compose -f docker-compose.yml run --volume $tmp_medimops:/tmp/medimops.jsonlines --entrypoint=/bin/ash crawler -c "scrapy crawl medimops -o /tmp/medimops.jsonlines"
        gzip --stdout $tmp_medimops >> data/$(date -u +"%Y-%m-%d").jsonlines.gz
        tmp_momox=$(mktemp)
        docker-compose -f docker-compose.yml run --volume $tmp_momox:/tmp/momox.jsonlines --entrypoint=/bin/ash crawler -c "scrapy crawl momox -o /tmp/momox.jsonlines"
        gzip --stdout $tmp_momox >> data/$(date -u +"%Y-%m-%d").jsonlines.gz
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update momox data
