on:
 workflow_dispatch:
 schedule:
  - cron: "0 */2 * * *"
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker-compose -f docker-compose.yml build crawler
    - name: crawl
      run: |
        tmp_file=$(mktemp)
        docker-compose -f docker-compose.yml run --volume $tmp_file:/tmp/momox.jsonlines --entrypoint=/bin/ash crawler -c "scrapy crawl momox -o /tmp/momox.jsonlines"
        touch data/$(date -u +"%Y-%m-%d").jsonlines.gz;
        gzip --stdout /tmp/momox.jsonlines >> data/$(date -u +"%Y-%m-%d").jsonlines.gz
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update momox data
