on:
 workflow_dispatch:
 schedule:
  - cron: "0 */2 * * *"
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker-compose -f docker-compose.yml build crawler
    - name: crawl
      run: touch data/$(date -u +"%Y-%m-%d").jsonlines.gz; docker-compose -f docker-compose.yml run --entrypoint=/bin/ash crawler -c "scrapy crawl momox -o momox.jsonlines; cat momox.jsonlines" | gzip --stdout >> data/$(date -u +"%Y-%m-%d").jsonlines.gz
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update momox data
